---
galaxy_info:
  description: Install core EC2
  author: mickmcgrath13
  company: Bitovi
  min_ansible_version: 2.5
  tags: core-ec2
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - web
    - nginx