name: 'Deploy Single VM Stackstorm to AWS EC2'
description: 'Deploy a Single VM Stackstorm to an AWS Virtual Machine (EC2)'
branding:
  icon: upload-cloud
  color: red
inputs:
  checkout:
    description: 'Specifies if this action should checkout the code'
    required: false
    default: "true"

  # AWS Configuration
  aws_access_key_id:
    description: 'AWS access key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_session_token:
    description: "AWS session token, if you're using temporary credentials"
    required: false
  aws_default_region:
    description: 'AWS default region'
    required: true
    default: us-east-1
  aws_ec2_instance_type:
    description: 'The AWS EC2 instance type'
    default: t2.medium
  aws_ec2_instance_profile:
    description: 'The AWS IAM instance profile to use for the EC2 instance. Use if you want to pass an AWS role with specific permissions granted to the instance'
  aws_resource_identifier:
    description: "Auto-generated by default so it's unique for org/repo/branch. Set to override with custom naming the unique AWS resource identifier for the deployment. Defaults to `${org}-${repo}-${branch}`."
  aws_create_vpc:
    description: 'Bool, whether an AWS VPC should be created in the action. Otherwise, the existing default VPC will be used.'
    default: "false"
  infrastructure_only:
    description: 'Set to true to provision infrastructure (with Terraform) but skip the app deployment (with ansible)'
    default: "false"

  # Terraform configuration
  tf_state_bucket:
    description: 'AWS S3 bucket to use for Terraform state. Defaults to `${org}-${repo}-${branch}-tf-state`'
    required: false

  # StackStorm configuration
  st2_auth_username:
    description: 'Username used by StackStorm standalone authentication. Set as a secret in GH Actions.'
    required: true
  st2_auth_password:
    description: 'Password used by StackStorm standalone authentication. Set as a secret in GH Actions.'
    required: true
  st2_packs:
    description: 'Comma separated list of packs to install. If you modify this option, be sure to also include `st2` in the list.'
    default: "st2"
  st2_ansible_extra_vars_file:
     description: "Relative path from project root to Ansible vars file. If you'd like to adjust more advanced configuration; st2 version, st2.conf, RBAC, chatops, auth, etc. See https://github.com/stackStorm/ansible-st2#variables for the full list of settings. The Ansible vars will take higher precedence over the GHA inputs."

  # Cleanup
  tf_stack_destroy:
    description: 'Set to "true" to Destroy the created AWS infrastructure for this instance'
    default: "false"
  tf_state_bucket_destroy:
    description: 'Force purge and deletion of tf_state_bucket defined. Any file contained there will be destroyed. tf_stack_destroy must also be true.'
    default: "false"

outputs:
  lb_url:
    description: 'The URL of the generated app'
    value: ${{ steps.deploy.outputs.lb_url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout if required
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3

    - name: Deploy with BitOps
      id: deploy
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        BITOPS_ENVIRONMENT: deployment
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
        AWS_DEFAULT_REGION: ${{ inputs.aws_default_region }}
        TF_STATE_BUCKET: ${{ inputs.tf_state_bucket }}
        TF_STATE_BUCKET_DESTROY: ${{ inputs.tf_state_bucket_destroy }}

        APP_PORT: ${{ inputs.app_port }}
        EC2_INSTANCE_PROFILE: ${{ inputs.aws_ec2_instance_profile }}
        EC2_INSTANCE_TYPE: ${{ inputs.aws_ec2_instance_type }}
        STACK_DESTROY: ${{ inputs.tf_stack_destroy }}
        AWS_RESOURCE_IDENTIFIER: ${{ inputs.aws_resource_identifier }}
        CREATE_VPC: ${{ inputs.aws_create_vpc }}

        # Skip ansible deployment if deploying only infrastructure
        ANSIBLE_SKIP_DEPLOY: ${{ inputs.infrastructure_only }}

        # ST2 config
        ST2_AUTH_USERNAME: ${{ inputs.st2_auth_username }}
        ST2_AUTH_PASSWORD: ${{ inputs.st2_auth_password }}
        ST2_PACKS: ${{ inputs.st2_packs }}
        BITOPS_ANSIBLE_EXTRA_VARS: ${{ inputs.st2_ansible_extra_vars_file }}
      run: |
        echo "running operations/_scripts/deploy/deploy.sh"
        $GITHUB_ACTION_PATH/operations/_scripts/deploy/deploy.sh

        echo "Setting up vars for GitHub"
        $GITHUB_ACTION_PATH/operations/_scripts/deploy/export_vars.sh

    # output results to GitHub
    - if: ${{ steps.deploy.outputs.lb_url != '' }}
      name: Print result created
      shell: bash
      run: |
        echo "## VM Created! :rocket:" >> $GITHUB_STEP_SUMMARY
        echo " ${{ steps.deploy.outputs.lb_url }}" >> $GITHUB_STEP_SUMMARY
    - if: ${{ steps.deploy.outputs.lb_url == '' }}
      name: Print result destroyed
      shell: bash
      run: |
        echo "## VM Destroyed! :boom:" >> $GITHUB_STEP_SUMMARY
        echo "Buckets and whole infrastructure should be gone now!" >> $GITHUB_STEP_SUMMARY
