- hosts: bitops_servers
  become: true
  environment: "{{ st2_proxy_env | default({}) }}"
  tasks:

  - name: Include install
    include_tasks: tasks/install.yml

  - name: Install st2
    include_tasks: tasks/st2.yml
