# APT
- name: apt - Install python3-passlib
  apt: 
    pkg: python3-passlib 
    state: present
  ignore_errors: yes

- name: apt - Install python-passlib
  apt: 
    pkg: python-passlib 
    state: present
  ignore_errors: yes

- name: apt - Install pip
  apt: 
    pkg: pip
    state: present
  ignore_errors: yes

# PIP
- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
  ignore_errors: yes

- name: pip - Install latest passlib with pip
  pip: name=passlib
  ignore_errors: yes

# YUM
- name: yum - Install latest passlib with pip
  ansible.builtin.yum:
    name: python-passlib
    state: latest
  ignore_errors: yes