# install st2
- name: Install st2 - StackStorm.mongodb
  include_role: StackStorm.mongodb
- name: Install st2 - StackStorm.rabbitmq
  include_role: StackStorm.rabbitmq
- name: Install st2 - StackStorm.redis
  include_role: StackStorm.redis
- name: Install st2 - StackStorm.st2repo
  include_role: StackStorm.st2repo
- name: Install st2 - StackStorm.st2
  include_role: StackStorm.st2
- name: Install st2 - StackStorm.nginx
  include_role: StackStorm.nginx
- name: Install st2 - StackStorm.st2web
  include_role: StackStorm.st2web
- name: Install st2 - StackStorm.nodejs
  include_role: StackStorm.nodejs
- name: Install st2 - StackStorm.st2chatops
  include_role: StackStorm.st2chatops
- name: Install st2 - StackStorm.st2smoketests
  include_role: StackStorm.st2smoketests