name: Deploy Testing for GHA Stackstorm

on:
  workflow_dispatch:
    inputs:
      aws_default_region:
        default: us-east-1
        type: string
      stack_destroy:
        required: true
        type: choice
        options:
          - false
          - true
      tf_state_bucket:
        type: string

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: bitovi/github-actions-deploy-stackstorm@copy_conf
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: ${{ github.event.inputs.aws_default_region }}
        stack_destroy: ${{ github.event.inputs.stack_destroy }}
        TF_STATE_BUCKET: ${{ github.event.inputs.tf_state_bucket }}
